# very_good_analysis based lint rules (Requirement 6.4)
# https://pub.dev/packages/very_good_analysis
include: package:very_good_analysis/analysis_options.yaml

analyzer:
  # Strict type checking
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  # Exclude generated files from analysis
  exclude:
    - "**/*.g.dart"
    - "**/*.gql.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/generated/**"
    - "build/**"
    - ".dart_tool/**"

  # Error handling configuration
  errors:
    # Treat missing returns as errors
    missing_return: error
    # Treat unused imports as warnings
    unused_import: warning
    # Treat unused local variables as warnings
    unused_local_variable: warning
    # Treat invalid annotations as errors
    invalid_annotation_target: error
    # Ignore deprecated_member_use for Riverpod parent parameter
    # See: https://github.com/rrousselGit/riverpod/issues/3261
    deprecated_member_use: ignore
    # Ignore deprecated XxxRef types from Riverpod code generation
    # These will be removed in Riverpod 3.0, but we use Ref instead where possible
    deprecated_member_use_from_same_package: ignore

linter:
  rules:
    # Project-specific customizations

    # Disable rules incompatible with freezed patterns
    sort_unnamed_constructors_first: false
    one_member_abstracts: false
    always_put_required_named_parameters_first: false
    overridden_fields: false
    annotate_overrides: false

    # Relax strict rules (especially for test files)
    lines_longer_than_80_chars: false
    # Disable unnecessary_lambdas for mocktail patterns
    # (mocktail requires when(() => method()) syntax)
    unnecessary_lambdas: false
    cascade_invocations: false
    require_trailing_commas: false
    avoid_redundant_argument_values: false
    prefer_int_literals: false
    prefer_const_constructors: false
    prefer_const_declarations: false
    prefer_const_literals_to_create_immutables: false

    # Allow print statements in debug mode (we'll use logger in production)
    avoid_print: false

    # Allow public members without documentation during initial development
    public_member_api_docs: false

    # Allow dynamic type in specific cases (GraphQL responses)
    avoid_dynamic_calls: false

    # Enforce consistent naming
    constant_identifier_names: true
    file_names: true
    library_names: true

    # Code style
    prefer_single_quotes: true
    always_use_package_imports: true
    sort_pub_dependencies: true

    # Null safety
    avoid_null_checks_in_equality_operators: true
    null_check_on_nullable_type_parameter: true

    # Error handling
    # Disable only_throw_errors: We use Failure sealed class with freezed
    # which doesn't extend Exception but provides exhaustive pattern matching
    only_throw_errors: false
    avoid_catching_errors: true

    # Async
    unawaited_futures: true
    avoid_void_async: true

    # Performance
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
