# very_good_analysis based lint rules (Requirement 6.4)
# https://pub.dev/packages/very_good_analysis
include: package:very_good_analysis/analysis_options.yaml

analyzer:
  # Strict type checking
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  # Exclude generated files from analysis
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/generated/**"
    - "build/**"
    - ".dart_tool/**"

  # Error handling configuration
  errors:
    # Treat missing returns as errors
    missing_return: error
    # Treat unused imports as warnings
    unused_import: warning
    # Treat unused local variables as warnings
    unused_local_variable: warning
    # Treat invalid annotations as errors
    invalid_annotation_target: error

linter:
  rules:
    # Project-specific customizations

    # Allow print statements in debug mode (we'll use logger in production)
    avoid_print: false

    # Allow public members without documentation during initial development
    public_member_api_docs: false

    # Allow dynamic type in specific cases (GraphQL responses)
    avoid_dynamic_calls: false

    # Prefer const constructors where possible
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

    # Enforce consistent naming
    constant_identifier_names: true
    file_names: true
    library_names: true

    # Code style
    prefer_single_quotes: true
    always_use_package_imports: true
    sort_pub_dependencies: true

    # Null safety
    avoid_null_checks_in_equality_operators: true
    null_check_on_nullable_type_parameter: true

    # Error handling
    only_throw_errors: true
    avoid_catching_errors: true

    # Async
    unawaited_futures: true
    avoid_void_async: true

    # Performance
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
