app_identifier("app.shelfie.shelfie")

submit_for_review(false)
automatic_release(false)

force(true)

metadata_path("./metadata")
skip_screenshots(true)

precheck_include_in_app_purchases(false)
run_precheck_before_submit(true)

app_review_information(
  demo_user: "demo@shelfie.app",
  demo_password: "ShelfieDemo2026!"
)
