app_identifier("app.shelfie.shelfie")

submit_for_review(false)
automatic_release(false)

force(true)

skip_screenshots(true)

precheck_include_in_app_purchases(false)
run_precheck_before_submit(true)

app_review_information(
  first_name: "空",
  last_name: "市古",
  phone_number: "+81 80-9647-4749",
  email_address: "igsr5.dev@gmail.com",
  demo_user: "demo@shelfie.app",
  demo_password: "ShelfieDemo2026!"
)
